"""Fetch the Google Fonts CSS for EB Garamond + Inter, extract woff2 URLs,
download each woff2 file, and generate a local @font-face CSS block.

Output files:
- themes/neddwyer/static/fonts/<filename>.woff2 (the actual font files)
- themes/neddwyer/static/css/fonts.css (the @font-face declarations)

The generated fonts.css can then be linked from head.html (replacing the
Google Fonts CDN link), and the woff2 files will be served from
neddwyer.com/fonts/.
"""

import re
import urllib.request
from pathlib import Path

ROOT = Path("/Users/nedwin/projects/neddwyer-com")
FONTS_DIR = ROOT / "themes" / "neddwyer" / "static" / "fonts"
FONTS_CSS = ROOT / "themes" / "neddwyer" / "static" / "css" / "fonts.css"

FONTS_DIR.mkdir(parents=True, exist_ok=True)

# Browser-realistic UA — Google Fonts serves woff2 only to modern browsers
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=EB+Garamond:ital,wght@0,400;0,500;0,700;1,400;1,500&"
    "family=Inter:wght@400;500;600&display=swap"
)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


print(f"Fetching CSS from Google Fonts ...")
css_bytes = fetch(CSS_URL)
css = css_bytes.decode("utf-8")
print(f"  Got {len(css):,} bytes of CSS")

# We want only the latin and latin-ext blocks — strip everything else
# Google's CSS includes /* cyrillic */, /* greek */, /* vietnamese */, etc.
# Each block is preceded by a /* range_name */ comment.

# Parse into (comment, @font-face block) pairs
blocks = re.split(r"(/\*\s*\S+\s*\*/)", css)
# blocks alternates: ['', '/* latin */', '<face>', '/* latin-ext */', '<face>', ...]

# Collect only latin and latin-ext
kept = []
for i in range(1, len(blocks) - 1, 2):
    comment = blocks[i]
    body = blocks[i + 1]
    if "/* latin */" in comment or "/* latin-ext */" in comment:
        kept.append((comment, body))

print(f"  Kept {len(kept)} font-face blocks (latin + latin-ext only)")

# Find all woff2 URLs in the kept blocks
all_text = "\n".join(c + b for c, b in kept)
woff2_urls = re.findall(r'url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)', all_text)
woff2_urls = list(dict.fromkeys(woff2_urls))  # dedup, preserve order
print(f"  Found {len(woff2_urls)} unique woff2 URLs")

# Download each woff2; map old URL → new local filename
url_to_local = {}
for url in woff2_urls:
    # Derive a clean filename from the URL
    raw_name = url.rsplit("/", 1)[-1]
    # Google's filenames are like: bWtR7VqIM8MZptiL_w0pzZk2nL98LIryw.woff2
    # That's already clean. Keep as-is.
    dest = FONTS_DIR / raw_name
    if not dest.exists() or dest.stat().st_size == 0:
        data = fetch(url)
        dest.write_bytes(data)
        print(f"  ↓ {raw_name} ({len(data):,} bytes)")
    else:
        print(f"  · {raw_name} (cached)")
    url_to_local[url] = f"/fonts/{raw_name}"

# Rewrite the CSS — replace Google URLs with local paths
local_css = all_text
for old_url, new_path in url_to_local.items():
    local_css = local_css.replace(old_url, new_path)

# Add font-display: swap to each @font-face block (Google already includes it,
# but doesn't hurt to ensure)
# Already has font-display: swap because we passed &display=swap in the URL.

# Prepend a header comment
header = (
    "/* Self-hosted EB Garamond + Inter — generated by\n"
    " * research/self_host_fonts.py from Google Fonts CSS API.\n"
    " * Re-run that script to refresh (e.g. if Google changes their woff2 hashes).\n"
    " */\n\n"
)

FONTS_CSS.parent.mkdir(parents=True, exist_ok=True)
FONTS_CSS.write_text(header + local_css)
print(f"\n  ✓ Wrote {FONTS_CSS.relative_to(ROOT)} ({len(local_css):,} bytes)")

# List final files
print(f"\nFinal font files in {FONTS_DIR.relative_to(ROOT)}:")
total_size = 0
for f in sorted(FONTS_DIR.iterdir()):
    size = f.stat().st_size
    total_size += size
    print(f"  {f.name}: {size:,} bytes")
print(f"\nTotal: {total_size:,} bytes ({total_size/1024:.1f} KB)")
